#!/usr/bin/env bash

APP="umbrellatest" # name of your release

BUILD_HOST="localhost" # host where to build the release
BUILD_USER="stevenbarragan" # local user at build host
BUILD_AT="/tmp/erlang/umbrellatest/builds" # build directory on build host


PRODUCTION_HOSTS="localhost" # deploy / production hosts separated by space
PRODUCTION_USER="stevenbarragan" # local user at deploy hosts
DELIVER_TO="/Users/stevenbarragan/elixir-builds/umbrellatest" # deploy directory on production hosts
