#!/usr/bin/env bash

APP="umbrellatest" # name of your release

# AUTO_VERSION=git-revision

BUILD_HOST="35.196.12.156" # host where to build the release
BUILD_USER="stevenbarragan" # local user at build host
BUILD_AT="/tmp/erlang/umbrellatest/builds" # build directory on build host


PRODUCTION_HOSTS="35.196.12.156" # deploy / production hosts separated by space
PRODUCTION_USER="stevenbarragan" # local user at deploy hosts
DELIVER_TO="/home/stevenbarragan/builds" # deploy directory on production hosts
